### 2.5 데이터 전처리
null값 처리 (제거 or 값을 메꾸기)
사이킷런은 문자입력을 허용하지 않음. 다 숫자로 해야..
주민번호나 아이디같은 거는 단순 식별하는 용도이면 굳이 데이터로 잇을 필요 없음 (인덱스 넣으면 되지?)

#### 데이터 인코딩

##### 레이블 인코딩
유니크값을 뽑아 일련번호를 매김. 매겨놓은 걸 딕셔너리라고 함.
서울은 1번 부산은 2번.. 이런 식으로
그리고 데이터에 서울이 있으면 딕셔너리를 보고 서울이 1번이구나, 해서 1번으로 바꿔주는 거
레이블 딕셔너리는 실제로는 리스트로 되어있음


In [1]:
from sklearn.preprocessing import LabelEncoder

In [2]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
encoder = LabelEncoder()
encoder.fit(items)
# 데이터를 정리해서 사전으로 만드는 작업
lables = encoder.transform(items)
# 만든 사전 보면서 데이터에 레이블 번호 붙여줌

# 인코더를 지워버리면 다음에 쓰려면 못 씀여.. 사전을 지워버리는 느낌인가

In [3]:
lables

array([0, 1, 4, 5, 3, 3, 2, 2])

In [4]:
encoder.transform(['냉장고'])

array([1])

In [5]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [7]:
encoder.inverse_transform([1])

array(['냉장고'], dtype='<U5')

In [9]:
encoder.inverse_transform(lables)

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

##### 원핫 인코딩
레이블이 숫자로 돼버리면 큰 숫자를 더 중요하다고 생각해버리거나.. 할 수도 있음. 멍충멍충
디시전트리는 상관 없지만 회귀분석쪽은 영향이 있을 수 있어서 다른 방법을 사용해야 함

해당하는 것만 1을 넣고 나머지는 0을 넣어 인코딩
데이터가 커지긴 함 ㅠㅠ 컬럼수만큼 늘어나야 하니까..
컬럼이 만개면 인코딩만 만개x만개 네?
1억갠가
희소행렬요..?? 밀집행렬요????????????? 그게 먼데요
뭐 또 해결할 방법이 있답니다


In [11]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [18]:
items
items_t = np.array(items).reshape(-1,1)
items_l = [['TV'],
       ['냉장고'],
       ['전자레인지'],
       ['컴퓨터'],
       ['선풍기'],
       ['선풍기'],
       ['믹서'],
       ['믹서']]
# np.array(items) items를 array로 만들고
# np.array(items).reshape(-1,1) 모양을 1,1로 만들

In [14]:
# oh_encoder = OneHotEncoder()
# oh_encoder.fit(items)
# oh_encoder.transform(items)

# ValueError: Expected 2D array, got 1D array instead:
# array=['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서'].
# Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

# 셰입이 안 맞는 거니 리셰입을 해라

In [26]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(items_l)
result = oh_encoder.transform(items_l)
result.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [25]:
#result만 찍으면 result의 정보?가 나옴. 그래서 .toarray() 붙여서 확인
# <8x6 sparse matrix of type '<class 'numpy.float64'>'
# 	with 8 stored elements in Compressed Sparse Row format>

<8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [ ]:
# items
# items_l = [['TV'],
#        ['냉장고'],
#        ['전자레인지'],
#        ['컴퓨터'],
#        ['선풍기'],
#        ['선풍기'],
#        ['믹서'],
#        ['믹서']]
# items_l처럼 바로 리스트로 나온 걸 넣어서 써도 되고
# items_t = np.array(items).reshape(-1,1) 처럼 변환한 걸 바로 items_t에 넣어서 써도 되고

In [20]:
oh_encoder.categories_

[array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype=object)]

In [23]:
oh_encoder.inverse_transform([[0., 1., 0., 0., 0., 0.]])
# 기본 데이터가 float라서 1. 0. 일케 나옴.. 내가 찍을 땐 그냥 1, 0 으로 찍어도 알아서 실수라고 생각해준댜

array([['냉장고']], dtype=object)

In [24]:
oh_encoder.transform([['냉장고']]).toarray()

array([[0., 1., 0., 0., 0., 0.]])

In [27]:
# 판다스에서 원핫인코딩 쉽게 하는 법
# 근디 겟더미즈는 레이블만 만들어지고 다시 쓰거나 할 수 없으니까 웬만하면 원핫인코더로 하는게 낫것다
import pandas as pd

In [28]:
df = pd.DataFrame({'item' : ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})

In [29]:
pd.get_dummies(df['item'])
# get_dummies()가 레이블 만들어주는 건가보당

TV  냉장고  믹서  선풍기  전자레인지  컴퓨터
0   1    0   0    0      0    0
1   0    1   0    0      0    0
2   0    0   0    0      1    0
3   0    0   0    0      0    1
4   0    0   0    1      0    0
5   0    0   0    1      0    0
6   0    0   1    0      0    0
7   0    0   1    0      0    0

#### 피처 스케일링과 정규화

가우....?? 시안???
단위 맞춰주는거
근데 왜 0~1 사이여



#### Standard Scaler
평균0 분산1인 값으로 만들어줌..?

In [31]:
from sklearn.datasets import load_iris


In [32]:
iris = load_iris(as_frame=True)
iris.data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [33]:
iris.data.mean()
# iris.data의 평균

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [34]:
iris.data.var()
# iris.data의 분산

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
scaler = StandardScaler()
scaler.fit(iris.data)
iris_scaled = scaler.transform(iris.data)

In [39]:
iris_df = pd.DataFrame(iris_scaled)

In [50]:
iris_df.mean().round(14)
# 평균을 0으로 만들어 준다고 하는데 완전 0은 아니고 0에 거의 가까운 수.. 소수점 반올림 하면 0으로 보임여 거의 14째자리까지 0이넴

0   -0.0
1   -0.0
2   -0.0
3   -0.0
dtype: float64

In [51]:
iris_df.var()

0    1.006711
1    1.006711
2    1.006711
3    1.006711
dtype: float64

#### MinMax Scaler
데이터 값을 0과 1 사이의 범위로 변환

In [52]:
from sklearn.preprocessing import MinMaxScaler

In [53]:
scaler = MinMaxScaler()
scaler.fit(iris.data)
iris_scaled = scaler.transform(iris.data)

In [57]:
iris_df = pd.DataFrame(iris_scaled)
iris_df.min(), iris_df.max()
# 미니멈0 맥시멈 1로 맞춰짐

(0    0.0
 1    0.0
 2    0.0
 3    0.0
 dtype: float64,
 0    1.0
 1    1.0
 2    1.0
 3    1.0
 dtype: float64)

In [58]:
iris_df.max(), iris.data.max()

(0    1.0
 1    1.0
 2    1.0
 3    1.0
 dtype: float64,
 sepal length (cm)    7.9
 sepal width (cm)     4.4
 petal length (cm)    6.9
 petal width (cm)     2.5
 dtype: float64)

#### 학습데이터와 테스트데이터의 스케일링 변환 시 유의점


In [59]:
train_array = np.arange(0,11).reshape(-1,1)
train_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [60]:
test_array = np.arange(0,6).reshape(-1,1)
test_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [61]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_array = scaler.transform(train_array)

In [62]:
train_array

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ]])

In [65]:
# scaler.fit(test_array)
test_array = scaler.transform(test_array)

In [67]:
test_array

array([[0.  ],
       [0.04],
       [0.08],
       [0.12],
       [0.16],
       [0.2 ]])

In [ ]:
????????????????????????????????????????????????????????????

### 2.6 사이킷런으로 수행하는 타이타닉 생존자 예측

## 3. 평가