
## 2. 사이킷으로 시작하는 머신러닝

### 2.4 모델 셀렉션 모듈 소개

#### 교차검증
과적합... 과소적합... 과대적합...
적갑...적합...저깝...

##### K폴드 교차 검증

In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

In [15]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)
kfold = KFold(n_splits=5, shuffle=True)

In [16]:
# 교차검증을 for문으로
cv_accuracy = []
n_iter = 0

for train_index, test_index in kfold.split(iris.data):
    # print(train_index)
    # print('---------')
    # print(test_index)
    X_train, X_test = iris.data[train_index], iris.data[test_index]
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = accuracy_score(y_test, pred)
    cv_accuracy.append(accuracy)
    print(n_iter, accuracy)
    print(y_test)

1 1.0
[0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2]
2 0.9333333333333333
[0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2]
3 0.9333333333333333
[0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
4 0.9
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2]
5 0.9666666666666667
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2]


In [17]:
np.round(np.mean(cv_accuracy), 4)

0.9467

##### Stratified K폴드

In [22]:
data = load_iris(as_frame=True)

In [23]:
data.target.value_counts()

0    50
1    50
2    50
Name: target, dtype: int64

In [27]:
kfold = KFold(n_splits=3, shuffle=False)
cv_accuracy = []
n_iter = 0

for train_index, test_index in kfold.split(iris.data):
    # print(train_index)
    # print('---------')
    # print(test_index)
    X_train, X_test = iris.data[train_index], iris.data[test_index]
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = accuracy_score(y_test, pred)
    cv_accuracy.append(accuracy)
    print(n_iter, accuracy)
    print(y_test)

# 0끼리, 1끼리, 2끼리 학습하고 다른 문제 푸니까 하나도 못 맞춤

1 0.0
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
2 0.0
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
3 0.0
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [28]:
kfold = KFold(n_splits=3, shuffle=True)
cv_accuracy = []
n_iter = 0

for train_index, test_index in kfold.split(iris.data):
    # print(train_index)
    # print('---------')
    # print(test_index)
    X_train, X_test = iris.data[train_index], iris.data[test_index]
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = accuracy_score(y_test, pred)
    cv_accuracy.append(accuracy)
    print(n_iter, accuracy)
    print(y_test)



1 0.92
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]
2 0.98
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 2 2 2 2 2 2 2 2 2 2 2 2]
3 0.94
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [29]:
from sklearn.model_selection import StratifiedKFold

In [30]:
kfold = StratifiedKFold(n_splits=3, shuffle=False)
cv_accuracy = []
n_iter = 0

for train_index, test_index in kfold.split(iris.data, iris.target):
    # print(train_index)
    # print('---------')
    # print(test_index)
    X_train, X_test = iris.data[train_index], iris.data[test_index]
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = accuracy_score(y_test, pred)
    cv_accuracy.append(accuracy)
    print(n_iter, accuracy)
    print(y_test)

1 0.98
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]
2 0.94
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]
3 0.98
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [44]:
kfold = StratifiedKFold(n_splits=3, shuffle=False)
cv_accuracy = []
n_iter = 0

iris = load_iris(as_frame=True)

for train_index, test_index in kfold.split(iris.data, iris.target):
    # print(train_index)
    # print('---------')
    # print(test_index)
    X_train, X_test = iris.data.iloc[train_index], iris.data.iloc[test_index]
    y_train, y_test = iris.target.iloc[train_index], iris.target.iloc[test_index]
    
    print('검증 데이터 분포', y_test.value_counts())
    
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = accuracy_score(y_test, pred)
    cv_accuracy.append(accuracy)
    print(n_iter, accuracy)
    # print(y_test)

검증 데이터 분포 0    17
1    17
2    16
Name: target, dtype: int64
1 0.98
검증 데이터 분포 0    17
2    17
1    16
Name: target, dtype: int64
2 0.94
검증 데이터 분포 1    17
2    17
0    16
Name: target, dtype: int64
3 0.98


##### 교차검증을 간편하게 - cross_val_score()

In [45]:
from sklearn.model_selection import cross_val_score

In [46]:
dt_clf = DecisionTreeClassifier(random_state=156)
iris = load_iris()
cross_val_score(dt_clf, iris.data, iris.target, cv=3)
# (모델, x값, y값, 몇등분)

array([0.98, 0.94, 0.98])

#### GridSearchCV 교차 검증과 최적 하이퍼 파라미터 튜닝을 한번에

하이퍼 파라미터(= 사람이 넣어주던 값)를 알아서 잘 넣어줌

In [47]:
grid_param = {
    'max_depth' : [1,2,3],
    'min_samples_split' : [2,3],
}
# ????
# 파라미터값 미리 정의?
# max_depth를 몇으로 줬을 때 제일 좋을지 모르니까 한번도 해보고 두번도 해보고 세번도 해보라고 정해줌


In [54]:
from sklearn.model_selection import GridSearchCV, train_test_split
import pandas as pd

In [50]:
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=121)

In [51]:
dtree = DecisionTreeClassifier()
grid_dtree = GridSearchCV(dtree, grid_param, cv=3, refit=True)
# GridSearchCV(
#     estimator, <모델
#     param_grid, <만들어놓은 파라미터값
#     *,<??
#     scoring=None, <???????
#     n_jobs=None,
#     refit=True,< 교차검증 경우의수 학습 다 해서 제일 결과가 좋았던 걸로 다시 돌려줌
#     cv=None,  <몇등분?
#     verbose=0,
#     pre_dispatch='2*n_jobs',
#     error_score=nan,
#     return_train_score=False,
# )

In [52]:
grid_dtree.fit(X_train, y_train)
# 학습시켜

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [53]:
grid_dtree.predict(X_test)

array([1, 2, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2,
       1, 1, 1, 1, 0, 0, 2, 2])

In [56]:
df = pd.DataFrame(grid_dtree.cv_results_)

In [57]:
df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score'],
      dtype='object')

In [58]:
df[['params', 'mean_test_score', 'rank_test_score',
       'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [59]:
grid_dtree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [60]:
grid_dtree.best_score_

0.975

In [65]:
pred = grid_dtree.best_estimator_.predict(X_test)
# 제일 좋았던 모델로 다시 학습시킨 예측값을 구함

In [66]:
accuracy_score(y_test, pred)

0.9666666666666667

### 2.5 데이터 전처리

#### 데이터 인코딩

##### 레이블 인코딩

##### 원핫 인코딩

#### 피처 스케일링과 정규화

#### Standard Scaler
